### ISSUE TITLE
Enhancement : Is it possible to add Postgres driver for DBM ? 

### ISSUE THREAD

**Issue by GeoffreyJohnen** [vlizBE/dcafs#16]
Hey ! 

I'd like to use dcafs to insert my data into a Postgresql DB. Is it possible to add the driver to do it ? 

Thanks a lot !

**Comment by michieltjampens** [comment]
Haven't got PostGres server running, can you try if this works?
[pg_version.zip](https://github.com/vlizBE/dcafs/files/6391518/pg_version.zip)

**Comment by michieltjampens** [comment]
[dcafs-0.9.2_pg4.zip](https://github.com/vlizBE/dcafs/files/6392344/dcafs-0.9.2_pg4.zip)
This should fix a couple things, but need to have a server running to properly figure the rest out.
