### ISSUE TITLE
"dailyfull" is received as sole body text of cruise status email

### ISSUE THREAD

**Issue by dietervansteenwegen** [vlizBE/dcafs#31]
As stated in the subject line, I've received a status email with subject line "Cruise started at 09:37." and simply "dailyfull" as body text.

Clearly, this does not represent the expected status report as I was waiting for a full daily report (which, to be clear, was not included). This leads to anxiety, not diminishing until the next (hopefully correct) report send by dcafs.

Also, there is no further information included in the email as how to resolve this and get the -much wanted- report.

**Comment by michieltjampens** [comment]
Not relevant to the dcafs source. Check the implementation for the cause.
